import DetailsComponent from '@/component/detailsPageComponent/DetailsComponent'
import { store } from '@/store/store'
import Head from 'next/head'
import React from 'react'
import { Provider } from 'react-redux'

function details() {
  return (
    <Provider store={store}>
      <Head>
        <title>Movie app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Tilt+Warp&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailsComponent />
    </Provider>
  )
}

export default details
